server:
  port: 29060
  max-http-header-size: 4048576

spring:
  profiles:
    active: dev
    include: default-${spring.profiles.active}
  application:
    name: system

#tenant:
#  exclusionTable:
#    - t_user